/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.CardLayout;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;
import paneles.Info_General_Panel;
import paneles.Metodos_Panel;
import paneles.Peticiones_Panel;
import paneles.Respuestas_Panel;


/**
 *
 * @author LENOVO
 */
public class Principal_Frame extends javax.swing.JFrame {

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Principal_Frame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("/recursos/iconos/Course_Room_Brand.png")));
        } catch (IOException ex) {
            
        }
        
        Peticiones_Panel peticiones_Panel = new Peticiones_Panel();
        principal_JPanel.add("Peticiones",peticiones_Panel);
        
        Respuestas_Panel respuestas_Panel = new Respuestas_Panel();
        principal_JPanel.add("Respuestas",respuestas_Panel);

        Metodos_Panel metodos_Panel = new Metodos_Panel();
        principal_JPanel.add("Metodos",metodos_Panel);
        
        Info_General_Panel info_General_Panel = new Info_General_Panel();
        principal_JPanel.add("Info_General", info_General_Panel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal_JPanel = new javax.swing.JPanel();
        barra_Menu_JMenuBar = new javax.swing.JMenuBar();
        peticiones_JMenu = new javax.swing.JMenu();
        respuestas_JMenu = new javax.swing.JMenu();
        metodos_JMenu = new javax.swing.JMenu();
        info_General_JMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servidor De CourseRoom");
        setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        principal_JPanel.setOpaque(false);
        principal_JPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(principal_JPanel, "card2");

        peticiones_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/request.png"))); // NOI18N
        peticiones_JMenu.setText("Peticiones");
        peticiones_JMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peticiones_JMenu.setFocusCycleRoot(true);
        peticiones_JMenu.setFocusPainted(true);
        peticiones_JMenu.setFocusTraversalPolicyProvider(true);
        peticiones_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        peticiones_JMenu.setOpaque(true);
        peticiones_JMenu.setRolloverEnabled(false);
        peticiones_JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peticiones_JMenuMouseClicked(evt);
            }
        });
        barra_Menu_JMenuBar.add(peticiones_JMenu);

        respuestas_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/responsibility.png"))); // NOI18N
        respuestas_JMenu.setText("Respuestas");
        respuestas_JMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        respuestas_JMenu.setFocusCycleRoot(true);
        respuestas_JMenu.setFocusPainted(true);
        respuestas_JMenu.setFocusTraversalPolicyProvider(true);
        respuestas_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        respuestas_JMenu.setOpaque(true);
        respuestas_JMenu.setRolloverEnabled(false);
        respuestas_JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestas_JMenuMouseClicked(evt);
            }
        });
        barra_Menu_JMenuBar.add(respuestas_JMenu);

        metodos_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/programming.png"))); // NOI18N
        metodos_JMenu.setText("Métodos");
        metodos_JMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        metodos_JMenu.setFocusCycleRoot(true);
        metodos_JMenu.setFocusPainted(true);
        metodos_JMenu.setFocusTraversalPolicyProvider(true);
        metodos_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        metodos_JMenu.setOpaque(true);
        metodos_JMenu.setRolloverEnabled(false);
        metodos_JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metodos_JMenuMouseClicked(evt);
            }
        });
        barra_Menu_JMenuBar.add(metodos_JMenu);

        info_General_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/information.png"))); // NOI18N
        info_General_JMenu.setText("Info General");
        info_General_JMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info_General_JMenu.setFocusCycleRoot(true);
        info_General_JMenu.setFocusPainted(true);
        info_General_JMenu.setFocusTraversalPolicyProvider(true);
        info_General_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        info_General_JMenu.setOpaque(true);
        info_General_JMenu.setRolloverEnabled(false);
        info_General_JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_General_JMenuMouseClicked(evt);
            }
        });
        barra_Menu_JMenuBar.add(info_General_JMenu);

        setJMenuBar(barra_Menu_JMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peticiones_JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peticiones_JMenuMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            ((CardLayout)principal_JPanel.getLayout()).show(principal_JPanel, "Peticiones");
        }
    }//GEN-LAST:event_peticiones_JMenuMouseClicked

    private void respuestas_JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestas_JMenuMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            ((CardLayout)principal_JPanel.getLayout()).show(principal_JPanel, "Respuestas");
        }
    }//GEN-LAST:event_respuestas_JMenuMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void metodos_JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metodos_JMenuMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            ((CardLayout)principal_JPanel.getLayout()).show(principal_JPanel, "Metodos");
        }
    }//GEN-LAST:event_metodos_JMenuMouseClicked

    private void info_General_JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_General_JMenuMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            ((CardLayout)principal_JPanel.getLayout()).show(principal_JPanel, "Info_General");
        }
    }//GEN-LAST:event_info_General_JMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_Menu_JMenuBar;
    private javax.swing.JMenu info_General_JMenu;
    private javax.swing.JMenu metodos_JMenu;
    private javax.swing.JMenu peticiones_JMenu;
    private javax.swing.JPanel principal_JPanel;
    private javax.swing.JMenu respuestas_JMenu;
    // End of variables declaration//GEN-END:variables

}
