/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;
import paneles.Peticiones_Panel;
import paneles.Respuestas_Panel;



/**
 *
 * @author LENOVO
 */
public class Principal_Frame extends javax.swing.JFrame {

    private Peticiones_Panel peticiones_Panel;
    private Respuestas_Panel respuestas_Panel;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Principal_Frame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("/recursos/iconos/Course_Room_Brand.png")));
        } catch (IOException ex) {
            
        }
        
        peticiones_Panel = new Peticiones_Panel();
        respuestas_Panel = new Respuestas_Panel();
        
        principal_JPanel.add("Peticiones",peticiones_Panel);
        principal_JPanel.add("Respuestas", respuestas_Panel);
        
        IniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal_JPanel = new javax.swing.JPanel();
        barra_Menu_JMenuBar = new javax.swing.JMenuBar();
        peticiones_JMenu = new javax.swing.JMenu();
        respuestas_JMenu = new javax.swing.JMenu();
        metodos_JMenu = new javax.swing.JMenu();
        informacion_Servidor_JMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servidor De CourseRoom");
        setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        principal_JPanel.setOpaque(false);
        principal_JPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(principal_JPanel, "card2");

        peticiones_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/request.png"))); // NOI18N
        peticiones_JMenu.setText("Peticiones");
        peticiones_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        peticiones_JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peticiones_JMenuMouseClicked(evt);
            }
        });
        barra_Menu_JMenuBar.add(peticiones_JMenu);

        respuestas_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/responsibility.png"))); // NOI18N
        respuestas_JMenu.setText("Respuestas");
        respuestas_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        respuestas_JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestas_JMenuMouseClicked(evt);
            }
        });
        barra_Menu_JMenuBar.add(respuestas_JMenu);

        metodos_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/programming.png"))); // NOI18N
        metodos_JMenu.setText("Métodos");
        metodos_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        barra_Menu_JMenuBar.add(metodos_JMenu);

        informacion_Servidor_JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/information.png"))); // NOI18N
        informacion_Servidor_JMenu.setText("Información Del Servidor");
        informacion_Servidor_JMenu.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        barra_Menu_JMenuBar.add(informacion_Servidor_JMenu);

        setJMenuBar(barra_Menu_JMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peticiones_JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peticiones_JMenuMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout)principal_JPanel.getLayout()).show(principal_JPanel, "Peticiones");
        }
    }//GEN-LAST:event_peticiones_JMenuMouseClicked

    private void respuestas_JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestas_JMenuMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout)principal_JPanel.getLayout()).show(principal_JPanel, "Respuestas");
        }
    }//GEN-LAST:event_respuestas_JMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_Menu_JMenuBar;
    private javax.swing.JMenu informacion_Servidor_JMenu;
    private javax.swing.JMenu metodos_JMenu;
    private javax.swing.JMenu peticiones_JMenu;
    private javax.swing.JPanel principal_JPanel;
    private javax.swing.JMenu respuestas_JMenu;
    // End of variables declaration//GEN-END:variables

    private void IniciarComponentes() {
  
  
    }
}
