/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import courseroom_server.CourseRoom_Server;

/**
 *
 * @author LENOVO
 */
public class Celda_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Celda_Panel
     * @param valor
     */
    public Celda_Panel(Object valor) {
        initComponents();
        
        valor_JLabel.setText(CourseRoom_Server.Formato_HTML_Central(valor.toString()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor_JLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 100));
        setMinimumSize(new java.awt.Dimension(315, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(315, 100));

        valor_JLabel.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        valor_JLabel.setForeground(new java.awt.Color(104, 194, 232));
        valor_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor_JLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valor_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel valor_JLabel;
    // End of variables declaration//GEN-END:variables
}
