/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import courseroom_server.CourseRoom_Server;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author LENOVO
 */
public class Celda_Panel extends javax.swing.JPanel implements Comparable<Object>{

    /**
     * Creates new form Celda_Panel
     * @param valor
     */
    public Celda_Panel(Object valor) {
        initComponents();
        
        valor_JLabel.setText(CourseRoom_Server.Formato_HTML_Central(valor.toString()));
        valor_JLabel.setForeground(new Color(104,194,232));
        
    }
    
    public JLabel Label(){
        return this.valor_JLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor_JLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 100));
        setMinimumSize(new java.awt.Dimension(315, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(315, 100));

        valor_JLabel.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        valor_JLabel.setForeground(new java.awt.Color(104, 194, 232));
        valor_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor_JLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valor_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public int compareTo(Object o) {
        if(o != null){
            
            if(o instanceof Celda_Panel celda){
                
                if(celda.Label().getText() != null &&
                        this.Label().getText() != null){
                    
                    return this.Label().getText().compareTo(celda.Label().getText());
                }
                else if (celda.Label().getText() != null &&
                        this.Label().getText() == null){
                    
                    return -1;
                }
                else if (celda.Label().getText() == null &&
                        this.Label().getText() != null){
                    return 1;
                }
                
                else{
                    return 0;
                }
            }
            
            return 1;
            
        }
        
        return 1;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel valor_JLabel;
    // End of variables declaration//GEN-END:variables
}
