/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import clases.Celda_Renderer;
import courseroom_server.CourseRoom_Server;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author LENOVO
 */
public class Info_General_Panel extends javax.swing.JPanel {

    
    public Info_General_Panel() {
        initComponents();
        
        logo_JLabel.setIcon(new ImageIcon(getClass().getResource("/recursos/imagenes/Course_Room_Brand_Blue.png")));

        courseroom_DB_JScrollPane.getVerticalScrollBar().setUnitIncrement(40);
        courseroom_DB_JScrollPane.getHorizontalScrollBar().setUnitIncrement(40);
        courseroom_Server_DB_JScrollPane.getVerticalScrollBar().setUnitIncrement(40);
        courseroom_Server_DB_JScrollPane.getHorizontalScrollBar().setUnitIncrement(40);
        
        Font gadugi = new Font("Gadugi", Font.BOLD, 16);
        courseroom_DB_JTable.getTableHeader().setFont(gadugi);
        courseroom_DB_JTable.getTableHeader().setBackground(logo_JLabel.getForeground());
        courseroom_DB_JTable.getTableHeader().setForeground(this.getBackground());
        courseroom_Server_DB_JTable.getTableHeader().setFont(gadugi);
        courseroom_Server_DB_JTable.getTableHeader().setBackground(logo_JLabel.getForeground());
        courseroom_Server_DB_JTable.getTableHeader().setForeground(this.getBackground());

        DefaultTableModel modelo = (DefaultTableModel) courseroom_DB_JTable.getModel();

        String[] insercion = new String[3];
        for (int i = 0; i < CourseRoom_Server.Faker().number().numberBetween(5, 15); i++) {
            insercion[0] = CourseRoom_Server.Faker().witcher().character();
            insercion[1] = String.valueOf(CourseRoom_Server.Faker().number().numberBetween(1, 100));
            insercion[2] = CourseRoom_Server.Faker().date().birthday(21, 22).toString();

            modelo.addRow(insercion);
        }
        
        modelo = (DefaultTableModel) courseroom_Server_DB_JTable.getModel();

        for (int i = 0; i < CourseRoom_Server.Faker().number().numberBetween(5, 15); i++) {
            insercion[0] = CourseRoom_Server.Faker().ancient().god();
            insercion[1] = String.valueOf(CourseRoom_Server.Faker().number().numberBetween(1, 100));
            insercion[2] = CourseRoom_Server.Faker().date().birthday(21, 22).toString();

            modelo.addRow(insercion);
        }

           
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_JLabel = new javax.swing.JLabel();
        courseroom_DB_JPanel = new javax.swing.JPanel();
        courseroom_DB_JScrollPane = new javax.swing.JScrollPane();
        courseroom_DB_JTable = new JTable(){
            public Class<?> getColumnClass(int column) {
                if (0 < this.getRowCount()) {
                    return getValueAt(0, column).getClass();
                } else {
                    return null;
                }
            }
        };
        courseroom_DB_JTable.setDefaultRenderer(String.class, new Celda_Renderer());
        courseroom_Server_DB_JPanel = new javax.swing.JPanel();
        courseroom_Server_DB_JScrollPane = new javax.swing.JScrollPane();
        courseroom_Server_DB_JTable = new JTable(){
            public Class<?> getColumnClass(int column) {
                if (0 < this.getRowCount()) {
                    return getValueAt(0, column).getClass();
                } else {
                    return null;
                }
            }
        };
        courseroom_DB_JTable.setDefaultRenderer(String.class, new Celda_Renderer());

        setBackground(new java.awt.Color(14, 30, 64));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        logo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        logo_JLabel.setForeground(new java.awt.Color(104, 194, 232));
        logo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_JLabel.setText("Info General");
        logo_JLabel.setMaximumSize(new java.awt.Dimension(175, 125));
        logo_JLabel.setMinimumSize(new java.awt.Dimension(175, 125));
        logo_JLabel.setPreferredSize(new java.awt.Dimension(175, 125));

        courseroom_DB_JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CourseRoom DB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 18), new java.awt.Color(104, 194, 232))); // NOI18N
        courseroom_DB_JPanel.setForeground(new java.awt.Color(104, 194, 232));
        courseroom_DB_JPanel.setOpaque(false);
        courseroom_DB_JPanel.setPreferredSize(new java.awt.Dimension(800, 609));
        courseroom_DB_JPanel.setLayout(new java.awt.CardLayout());

        courseroom_DB_JScrollPane.setBorder(null);

        courseroom_DB_JTable.setAutoCreateRowSorter(true);
        courseroom_DB_JTable.setBackground(new java.awt.Color(14, 30, 64));
        courseroom_DB_JTable.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        courseroom_DB_JTable.setForeground(new java.awt.Color(104, 194, 232));
        courseroom_DB_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tabla", "# Registros", "Actualizado"
            }
        ));
        courseroom_DB_JTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        courseroom_DB_JTable.setRowHeight(100);
        courseroom_DB_JTable.setRowMargin(10);
        courseroom_DB_JTable.setShowGrid(true);
        courseroom_DB_JTable.setRowSorter(new TableRowSorter(courseroom_DB_JTable.getModel()));
        courseroom_DB_JScrollPane.setViewportView(courseroom_DB_JTable);

        courseroom_DB_JPanel.add(courseroom_DB_JScrollPane, "card2");

        courseroom_Server_DB_JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CourseRoom Server DB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 18), new java.awt.Color(104, 194, 232))); // NOI18N
        courseroom_Server_DB_JPanel.setForeground(new java.awt.Color(104, 194, 232));
        courseroom_Server_DB_JPanel.setOpaque(false);
        courseroom_Server_DB_JPanel.setPreferredSize(new java.awt.Dimension(800, 609));
        courseroom_Server_DB_JPanel.setLayout(new java.awt.CardLayout());

        courseroom_Server_DB_JScrollPane.setBorder(null);

        courseroom_Server_DB_JTable.setAutoCreateRowSorter(true);
        courseroom_Server_DB_JTable.setBackground(new java.awt.Color(14, 30, 64));
        courseroom_Server_DB_JTable.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        courseroom_Server_DB_JTable.setForeground(new java.awt.Color(104, 194, 232));
        courseroom_Server_DB_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tabla", "# Registros", "Actualizado"
            }
        ));
        courseroom_Server_DB_JTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        courseroom_Server_DB_JTable.setRowHeight(100);
        courseroom_Server_DB_JTable.setRowMargin(10);
        courseroom_Server_DB_JTable.setShowGrid(true);
        courseroom_DB_JTable.setRowSorter(new TableRowSorter(courseroom_DB_JTable.getModel()));
        courseroom_Server_DB_JScrollPane.setViewportView(courseroom_Server_DB_JTable);

        courseroom_Server_DB_JPanel.add(courseroom_Server_DB_JScrollPane, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseroom_DB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseroom_Server_DB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseroom_Server_DB_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(courseroom_DB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel courseroom_DB_JPanel;
    private javax.swing.JScrollPane courseroom_DB_JScrollPane;
    private javax.swing.JTable courseroom_DB_JTable;
    private javax.swing.JPanel courseroom_Server_DB_JPanel;
    private javax.swing.JScrollPane courseroom_Server_DB_JScrollPane;
    private javax.swing.JTable courseroom_Server_DB_JTable;
    private javax.swing.JLabel logo_JLabel;
    // End of variables declaration//GEN-END:variables
}
