/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import datos.colecciones.Lista;


/**
 *
 * @author LENOVO
 */
public class Respuestas_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Peticiones_Panel
     */
    public Respuestas_Panel() {
        initComponents();
        
        peticiones_JScrollPane.getViewport().setOpaque(false);
        peticiones_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        peticiones_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        Lista<String> lista = new Lista<>();
        
        lista.push_back("Respuesta Ascendente","Cliente Ascendente","Fecha Ascendente",
                "Respuesta Descendente","Cliente Descendente","Fecha Descendente");
        
        Titulo_Panel titulo_Panel = new Titulo_Panel("Respuestas", lista);
        
        peticiones_JPanel.add(titulo_Panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peticiones_JScrollPane = new javax.swing.JScrollPane();
        peticiones_JPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(14, 30, 64));
        setLayout(new java.awt.BorderLayout());

        peticiones_JScrollPane.setOpaque(false);

        peticiones_JPanel.setOpaque(false);
        peticiones_JPanel.setLayout(new javax.swing.BoxLayout(peticiones_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        peticiones_JScrollPane.setViewportView(peticiones_JPanel);

        add(peticiones_JScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel peticiones_JPanel;
    private javax.swing.JScrollPane peticiones_JScrollPane;
    // End of variables declaration//GEN-END:variables
}
